# Generated by Django 2.0.7 on 2019-02-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='some staff to do')),
                ('start_time', models.DateField(auto_now_add=True)),
                ('build_time', models.TimeField()),
            ],
        ),
    ]
