# Generated by Django 2.0.7 on 2019-02-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantodo',
            name='build_time',
        ),
        migrations.AddField(
            model_name='plantodo',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plantodo',
            name='description',
            field=models.TextField(default='some staff to do'),
        ),
    ]
