# Generated by Django 2.0.7 on 2019-02-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0002_auto_20190207_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantodo',
            name='Post_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantodo',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
